### PR TITLE
FIX: Announcement are not displayed in infinite loop  

### PR DESCRIPTION
**Pull request by YassinNouh21**
📝 **Summary**
---
This PR fixes the bug introduced in this ticket #1000 

**Description**
---
This PR focuses on streamlining how announcement items, including videos, are managed and transitioned within the app. Key updates include:

- **AnnouncementWorkFlowItem Class Enhancement**: Redefined the structure for announcement items, focusing on essential functionalities and removing redundant attributes like minimum duration.

- **State Management with Riverpod**: Transitioned to Riverpod for state management, markedly improving the app's handling of dynamic content flows, particularly with video playback and automatic transitions.

- **VideoWorkflowNotifier for Video Management**: Launched `VideoWorkflowNotifier`, a state notifier dedicated to managing video playback within the workflow, facilitating precise control over video-related actions and enhancing user experience.

- **Introduce PageView Builder for Workflow**: Implemented a PageView Builder to handle screen transitions and displays more efficiently.

**Tests**
---
🧪 **Use case 1: Skipping Items**
---
💬 **Description:** Verified that items marked as `skip` are correctly omitted from the workflow, ensuring the transition logic accurately jumps over skipped items.

📷 **Screenshots or GIFs (if applicable):**

https://github.com/mawaqit/android-tv-app/assets/70436855/19712eae-e2a7-411b-8d78-f5d02a832cfd

skip

🧪 **Use case 2: Displaying All Items Including Videos, Images, and Text**
---
💬 **Description:** Conducted thorough testing to confirm that all types of content are properly displayed and transitioned within the workflow. This includes seamless handling of videos, images, and text announcements, with special attention to the automatic transition after video playback concludes.

📷 **Screenshots or GIFs (if applicable):**

test-all

all

**Checklist:**
---
- [x] **Coding Standards:** Reviewed to ensure adherence to the project's coding standards.
- [x] **Testing:** All changes have been tested across various scenarios and work as expected.
- [x] **Merge Conflicts:** Any conflicts with the main/development branch have been resolved.
- [x] **Branch Status:** The branch is up-to-date with the target branch (main/development).

### CODE REVIEW

**Comment by ibrahim-zehhaf-mawaqit** [comment]
I tested your branch on the emulator and still have issue, ID 1, announcement mode
Please exit the app and open it again after changing the mode

image

**Comment by ibrahim-zehhaf-mawaqit** [comment]
ok

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Can you update your branch with master please, so I can test correctly

**Comment by ibrahim-zehhaf-mawaqit** [comment]
It works but it's not perfect

- [ ] when I add a message from the admin console, it's not displayed automatically, I need to exit the app and open it again. All data are synchronized every one minute
- [ ] When the last message finish we have a bad behavior, we see short farward to the first one, it should be an infinite loop, like a carousel/slider

**Comment by ghassenbenzahra123** [comment]
> It works but it's not perfect
> 
> * [ ]  when I add a message from the admin console, it's not displayed automatically, I need to exit the app and open it again. All data are synchronized every one minute
> * [ ]  When the last message finish we have a bad behavior, we see short farward to the first one, it should be an infinite loop, like a carousel/slider

@ibrahim-zehhaf-mawaqit  I'll wait for Yassin's update to review the code.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@YassinNouh21 there in another pb (a regression) on the main screen (prayer times screen)
When the messages appears, 2 messages are alternating non stop
https://www.awesomescreenshot.com/video/24889297?key=aff19df747365837bca23c778359790f

The good behavior is 
All the messages for non mosque and all except videos for mosques must scroll until the last one and come back to the prayer times screen

**Review by ghassenbenzahra123 — APPROVED** [review]
LGTM! good work Yassin

**Pull request merged**
