### PR TITLE
feat: New Version Update Notifications

### PR DESCRIPTION
**Pull request by YassinNouh21**
📝 **Summary**
---
**This PR addresses several key related to the app update feature for users. It integrates functionality to check for updates, notify users, and direct them to the store for updating the app.**

**Description**
---
- Implemented the `AppUpdateNotifier` and `AppUpdateState` to manage app update statuses dynamically.
- Added support for localization with new entries related to app updates, ensuring users receive messages in their preferred language.
- Introduced new dependencies (`upgrader`, `flash`, and `open_store`) to facilitate checking for updates and notifying users.
- Extended the UI to include update alerts in both landscape and portrait, improving user engagement and ensuring that updates are promptly noticed and applied.

**Tests**
---
🧪 **Use case 1**
---
💬 **Description:** Verifying the update notification flow
- Triggered an update scenario to see if the app correctly identifies the update status and notifies the user accordingly.
- Tested in both landscape and portrait modes to ensure the update prompt is displayed correctly across different orientations.
- Confirmed that tapping on the update prompt leads the user to the app's store page for an update.

📷 **Screenshots or GIFs (if applicable):**

**Checklist:**
---
- [x] **Coding Standards:** Reviewed the code to ensure it follows the project's coding standards.
- [x] **Testing:** Conducted tests on the changes, and they work as expected.
- [x] **Merge Conflicts:** Resolved any merge conflicts with the latest main/development branch.
- [x] **Branch Status:** Ensured the branch is up-to-date with the target branch (main/development).

### CODE REVIEW

**Review by ghassenbenzahra123 — COMMENTED** [review]
LGTM works as expected ! 

- Prompt the user with a flash message daily between Maghrib and Isha salat to update the app if there is an update available that lasts 30 seconds.

@ibrahim-zehhaf-mawaqit  does this conditions answer the required behavior ? so i can merge the branch.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> LGTM works as expected !
> 
> * Prompt the user with a flash message daily between Maghrib and Isha salat to update the app if there is an update available that lasts 30 seconds.
> 
> @ibrahim-zehhaf-mawaqit does this conditions answer the required behavior ? so i can merge the branch.

The alert is displayed during 30 sec right ?
And of the user dismisses the alert it will not be displayed until a new release is available ?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> It appears every week between Isha and Maghreb prays. @ibrahim-zehhaf-mawaqit

thanks but you don't answer my questions ;)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Ok so please update the behavior 

- If the user dismiss the alert it will be hidden until a new release available
- The feature auto update checking mut be disabled in settings

**Comment by YassinNouh21** [comment]
@ghassenbenzahra123 I updated the pr with the new requirements

**Review by ghassenbenzahra123 — APPROVED** [review]
LGTM!

**Pull request merged**
