### PR TITLE
Fix/ Center information widget

### LINKED ISSUE #1319: Vertical mode - information are not centered
IMG_3951

### PR DESCRIPTION
**Pull request by ghassenbenzahra123**
📝 **Summary**
---
This PR fixes #1319 

📝 **Screenshots**
---

Screenshot_1726480940

**Checklist:**
---
- [x] **Coding Standards:** I have reviewed my code to ensure it follows the project's coding standards.
- [x] **Testing:** I have tested the changes and they work as expected.
- [x] **Merge Conflicts:** I have resolved any merge conflicts with the latest main/development branch.
- [x] **Branch Status:** The branch is up-to-date with the target branch (main/development).

### CODE REVIEW

**Comment by YassinNouh21** [comment]
This PR introduces new issue at the slider announcement message

image

**Review by YassinNouh21 — COMMENTED** [review]
- IntrinsicWidth and Expanded: Wrapping an IntrinsicWidth inside an Expanded might cause layout issues because they have conflicting constraints. Expanded tries to expand its child to fill available space, whereas IntrinsicWidth tries to size itself to its child's intrinsic width.
**Recommendation**: Test this layout thoroughly to ensure it doesn't produce unexpected behavior on different screen sizes or orientations.

----

// Before
alignment: Alignment(-1, 1),

// After
alignment: Alignment.topLeft,

**Comment by ghassenbenzahra123** [comment]
> This PR introduces new issue at the slider announcement message
> 
> image

Screenshot_1727123516
@YassinNouh21

**Review by YassinNouh21 — APPROVED** [review]

**Comment by YassinNouh21** [comment]
@ghassenbenzahra123 can u test my edits if u are ok for changes then accept

**Comment by ghassenbenzahra123** [comment]
> @ghassenbenzahra123 can u test my edits if u are ok for changes then accept

@YassinNouh21  please readjust the height of the container and make the logo at the bottom like it was implemented 

Screenshot_1728475055

Screenshot_1728475100

**Pull request merged**
