### PR TITLE
add loading spinner in the mosque selector tile

### PR DESCRIPTION
**Pull request by ismaelAbogabal**
# Issues

after adding the precaching for images, and voices this mosque selector tile become irresponsive. for better UX app should give the user instant feedback that he take his order. 

# Solution

for instant feedback, I added a spinner in the mosque tile user tapped on. so once he tap on the time the spinner will start.

### CODE REVIEW

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal I didn't understand, please provide a video

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
Now it's very fast. it will take a little longer once we merge the image pre-caching pull request.

https://github.com/mawaqit/android-tv-app/assets/63953869/8b718970-3dc2-4e9f-979b-9e30202e2716

**Review by ibrahim-zehhaf-mawaqit — APPROVED** [review]

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal please resolve the conflict

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit  Conflict solved

**Pull request merged**
