### PR TITLE
944 random hadiths are not displayed if the option disable hadith between 2 prayers is enabled

### PR DESCRIPTION
**Pull request by YassinNouh21**
📝 **Summary**
This PR refactors the `isDisableHadithBetweenSalah` method in the `MosqueHelpersMixin` class. The method's functionality has been expanded to handle a range of disabled periods rather than a single period. Additionally, the method's readability have been improved by breaking down its logic into more manageable parts.

**This PR for issue**  #944 

💬 **Description:**
- Implemented `_parseDisablingPeriods` private method to extract the logic for parsing the start and end periods of the disabling interval.
- Updated `isHadithDisabledDuringSalah` method to use the parsed start and end periods for determining if the Hadith feature is disabled.
- Handle the null values that might occur after parsing. 

**Issue Solved**
The original implementation of `isDisableHadithBetweenSalah` only considered a single period for disabling the Hadith feature, which limited its functionality. This update addresses these issues by:

1. **Extending Functionality**: The method now correctly handles a range of periods during which the Hadith feature should be disabled, as defined in the mosque configuration.

📷 **Screenshots or GIFs (if applicable):**

### First test case:
---

Setup the Disable hadiths between Asr and Maghrib and test. When the current time is between Fajr and Duhr prayers 

image

https://github.com/mawaqit/android-tv-app/assets/70436855/f05e5654-ad98-4ff4-8d08-e6af4ff8de0c

### Second test case:
---

Setup the Disable hadiths between Asr and Maghrib and test. When the current time is between Maghrib and Isha prayers 

image

https://github.com/mawaqit/android-tv-app/assets/70436855/50b691cf-0246-4629-a440-a50121d66ed1

### Third test case:
---

Setup the Disable hadiths between Asr and Maghrib and test. When the current time is between Asr and Maghrib prayers 

image

**Checklist:**
---
- [x] **Coding Standards:** I have reviewed my code to ensure it follows the project's coding standards.
- [x] **Testing:** I have tested the changes and they work as expected.
- [x] **Merge Conflicts:** I have resolved any merge conflicts with the latest main/development branch.
- [x] **Branch Status:** The branch is up-to-date with the target branch (main/development).

### CODE REVIEW

**Comment by ibrahim-zehhaf-mawaqit** [comment]
I have a blank page
image

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ghassenbenzahra123 need your approve

**Comment by YassinNouh21** [comment]
@ibrahim-zehhaf-mawaqit 

I hope you're doing well! I've been working on the pull request, and I believe I've identified the issue of the blank screen.

It appears that the blank screen is caused by the asynchronous handling of the Hadith fetch operation. Instead of using [`then`](https://github.com/mawaqit/android-tv-app/blob/6e79b439cb90e79c389bbc4d5a07e16551754400/lib/src/pages/home/sub_screens/RandomHadithScreen.dart#L31), which doesn't wait for the Hadith to fetch, I recommend implementing an `async/await`.

I've applied this patch on GitHub for you to review, and I think you'll notice a significant difference when fetching the first Hadith. It consistently returns null even on the main branch, which indicates a separate issue.

[Reproduce_the_error_of_blank_screen.patch](https://github.com/mawaqit/android-tv-app/files/13811706/Reproduce_the_error_of_blank_screen.patch)

While working on this, I also realized that we could improve our state management by implementing a loading state and data state, along with an error state. For example, when fetching the Hadith, we can display a "Please wait..." message to provide a better user experience.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Thank you @YassinNouh21 for this investigation
No the hadith is displayed only on success so no issue in the normal workflow, it's a background action, we don't need a message or any loader.

My screenshot shows a blank screen when I go directly the hadith screen from developer menu

**Comment by YassinNouh21** [comment]
Does it become blank the first time @ibrahim-zehhaf-mawaqit ?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
I will test on my box, I think I have an issue with emulator

**Comment by ibrahim-zehhaf-mawaqit** [comment]
I'll wait for @ghassenbenzahra123 to review the code and test so I can merge

**Review by ghassenbenzahra123 — APPROVED** [review]
LGTM. thoroughly tested all possible configurations to disable the hadiths, and it is functioning correctly. 
The blank screen issue will persist even on the box, but it is unrelated to this pull request, as explained by Yassin, its a separate issue.

**Pull request merged**
