### PR TITLE
898 enable select the hadith language based on the app langauge overwrite the backend chosen value

### PR DESCRIPTION
**Pull request by YassinNouh21**
📝 **Summary**
---
**This PR for issue**  #898

**Description**
---
This PR introduces functionality to allow users to select their preferred language for Hadiths in the application. The available Hadith languages have been added to `intl_en.arb`. The user's language choice is saved using `SharedPreferences` in `AppLanguage.dart`. A UI has been implemented for users to choose their preferred language. Additionally, the `RandomHadithMixin` has been utilized to fetch Hadiths in the selected language, ensuring a personalized experience for the user.

**Tests**
---
🧪 **Use case 1: Selecting and Saving Preferred Language**
---
💬 **Description:** 
Tested the functionality where users can select their preferred Hadith language from the newly implemented UI. The selected language is then saved using `SharedPreferences`. On reopening the app, the selected language is successfully retained.

📷 **Screenshots or GIFs (if applicable):**
[Include screenshots or GIFs demonstrating the language selection and persistence across app restarts]

image
image

**Checklist:**
---
- [x] **Coding Standards:** I have reviewed my code to ensure it follows the project's coding standards.
- [x] **Testing:** I have tested the changes and they work as expected. The language selection and Hadith fetching work seamlessly.
- [x] **Merge Conflicts:** I have resolved any merge conflicts with the latest main/development branch.
- [x] **Branch Status:** The branch is up-to-date with the target branch (main/development).

---

### CODE REVIEW

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ghassenbenzahra123 can you add your review please

**Review by ghassenbenzahra123 — APPROVED** [review]
Tested all the hadith languages, offline mode and the rest of the screens LGTM. 
Great work Yassin.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
I tested the branch and noticed some issues

- [ ] The divider in the language selector is not good 
- [ ] The ID input not ok 
- [ ] The buttons 

* Current UI
   image   
   image
   image

* Your branch
  image
  image

- [ ] Some languages are not working like Portugues and German, I have a blank screen when I go to hadith screen, please be sur all languages are working

**Comment by YassinNouh21** [comment]
> I tested the branch and noticed some issues
> 
> * [ ]  The divider in the language selector is not good
> * [ ]  The ID input not ok
> 
> * Current UI
>   image
>   image
> * Your branch
>   image
>   image
> 
> * [ ]  Some languages are not working like Portugues and German, I have a blank screen when I go to hadith screen, please be sur all languages are working

I reviewed it back with @ghassenbenzahra123 in a meeting and those issues didn't occur.

**Pull request merged**
