### PR TITLE
Fix #955 Add app and os version to sentry logs

### LINKED ISSUE #955: Add app and OS version in sentry logs
We need to identify the version of the app and android OS on sentry logs

### PR DESCRIPTION
**Pull request by ghassenbenzahra123**
📝 **Summary**
---
**This PR fixes**  #955 

**Description**
---
- [x] This fix adds app & os version tags on sentry issue reports. 
- [x] Add reporting for device info even if an issue occurs on the onboarding process. 

 [📈](https://emojipedia.org/chart-increasing) **Results**
---

1.  **App & os version on sentry tags**

  

2.  **Report when mosque uuid is not set (e.g., issue in onBoarding process)**

  

 3. **Full Report when mosque uuid is set**

  

**Checklist:**
---
- [x] **Coding Standards:** I have reviewed my code to ensure it follows the project's coding standards.
- [x] **Testing:** I have tested the changes and they work as expected.
- [x] **Merge Conflicts:** I have resolved any merge conflicts with the latest main/development branch.
- [x] **Branch Status:** The branch is up-to-date with the target branch (main/development).

### CODE REVIEW

**Comment by YassinNouh21** [comment]
In [line](https://github.com/mawaqit/android-tv-app/blob/21547b0ac871cb4c6374cfa55d5b6a8f4910c7d7/lib/src/helpers/CrashlyticsWrapper.dart#L48) Do you think adding language would be good for debugging?

**Comment by ghassenbenzahra123** [comment]
> In [line](https://github.com/mawaqit/android-tv-app/blob/21547b0ac871cb4c6374cfa55d5b6a8f4910c7d7/lib/src/helpers/CrashlyticsWrapper.dart#L48) Do you think adding language would be good for debugging?

All the user-data fetched in the above logs were already collected by @ibrahim-zehhaf-mawaqit  & @ismael-abogabal-mawaqit    . It can beneficial to figure out if there is an issue with a certain language.

**Comment by YassinNouh21** [comment]
I also Tested it 
image

**Review by YassinNouh21 — APPROVED** [review]
It looks good for me LGTM  👍

**Pull request merged**
