### PR TITLE
Fix check connectivity

### PR DESCRIPTION
**Pull request by YassinNouh21**
📝 **Summary**
---
**This PR for issue**: Implement Internet connectivity. 

**Description**
---
This Pull Request introduces a`ConnectivityService` for monitoring network connectivity. it introduces Riverpod package for dependable state management and includes classes such as `ConnectivityProvider`, `AddressCheckOptions`, and `AddressCheckResult`. The service is designed to check against a list of specified internet addresses every **3 seconds** to determine the connectivity status. This feature is crucial for applications that rely on a consistent and reliable internet connection.

**Tests**
---
🧪 **Use case 1**
---
💬 **Description:** Testing connectivity to predefined addresses (Google and CloudFlare) using `ConnectivityService`.
 
📷 **Screenshots or GIFs (if applicable):** _Screenshots of the app successfully determining the connectivity status._

**Checklist:**
---
- [x] **Coding Standards:** I have reviewed my code to ensure it follows the project's coding standards.
- [x] **Testing:** I have tested the changes and they work as expected.
- [x] **Merge Conflicts:** I have resolved any merge conflicts with the latest main/development branch.
- [x] **Branch Status:** The branch is up-to-date with the target branch (main/development).

### CODE REVIEW

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Wow, A lot of code for a small feature ;) 
Internet status is used only and just for displaying a small icon in the top left corner of the TV.

I think just an http HEAD call (not GET to preserve data bandwidth)  with  of google.com, if success then internet ok if fail then ko. and we don't need to check every 3 sec, 10 or 15 sec is sufficient to reduce internet traffic 

`curl --head https://www.google.com`

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ghassenbenzahra123 what do you think ?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Ok thanks, can you approve the PR ?
Please don't wait me to do the review and approve, it's very important, I can't merge non-approved PR

**Review by ghassenbenzahra123 — COMMENTED** [review]
Increase time for checking every 10 secoonds please Yassin.

**Comment by ghassenbenzahra123** [comment]
> Ok thanks, can you approve the PR ? Please don't wait me to do the review and approve, it's very important, I can't merge non-approved PR

I reviewed it and added the suggested change. I'll make sure to review the PRs as quickly as possible in the future.

**Review by ghassenbenzahra123 — APPROVED** [review]

**Pull request merged**
