### PR TITLE
feat: update Quran configuration file URL to tv_config.json

### PR DESCRIPTION
**Pull request by YassinNouh21**
## 📝 Summary

This PR addresses the following issues:

- **[#1378](https://github.com/mawaqit/android-tv-app/issues/1378):** Align Hafs design with Warsh style  
- **[#1462](https://github.com/mawaqit/android-tv-app/issues/1462):** Update configuration file to use `tv_config.json`

---

## Description

This update modifies the constant `quranMoshafConfigJsonUrl` in `constants.dart` to use the `tv_config.json` file. This change ensures compatibility with the new configuration requirements for the Android TV app, aligning with the project's milestones and enhancing the user experience.

---

### 🧪 Use Case 1
- **💬 Description:**  
  Verify that the app successfully loads the configuration from `tv_config.json` without errors.

- **📷 Screenshots or GIFs (if applicable):**  

quran_config

---

## Checklist

- [x] **Coding Standards:** Code adheres to project coding standards.  
- [x] **Testing:** Changes tested and verified to work as expected.  
- [x] **Merge Conflicts:** Resolved any merge conflicts with the target branch.  
- [x] **Branch Status:** Branch is up-to-date with the main/development branch.

### CODE REVIEW

**Comment by YassinNouh21** [comment]
@ibrahim-zehhaf-mawaqit
i implemented that if there is a new update version. because now in hafs we have v1.0 and v2.0. 
for this what do u think should we show a pop up for the user or just leave it ?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> @ibrahim-zehhaf-mawaqit i implemented that if there is a new update version. because now in hafs we have v1.0 and v2.0. for this what do u think should we show a pop up for the user or just leave it ?
> 
> image
> 
> Like this ?

Yes the popup is, just change the title, A new version of the xxxx mushaf is available 
xxxx = hafs | warsh

**Comment by YassinNouh21** [comment]
> > @ibrahim-zehhaf-mawaqit i implemented that if there is a new update version. because now in hafs we have v1.0 and v2.0. for this what do u think should we show a pop up for the user or just leave it ?
> > image
> > Like this ?
> 
> Yes the popup is, just change the title, A new version of the xxxx mushaf is available xxxx = hafs | warsh

i think it will be annoying every time he opens the quran to show him

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> > > @ibrahim-zehhaf-mawaqit i implemented that if there is a new update version. because now in hafs we have v1.0 and v2.0. for this what do u think should we show a pop up for the user or just leave it ?
> > > image
> > > Like this ?
> > 
> > 
> > Yes the popup is, just change the title, A new version of the xxxx mushaf is available xxxx = hafs | warsh
> 
> i think it will be annoying every time he opens the quran to show him

Only if a new version is available 
If he downloads the popup doesn't appear again

**Review by ghassenbenzahra123 — APPROVED** [review]
LGTM!

**Pull request merged**
