### PR TITLE
refactor(ui): center the `buildMosqueName` in `mosque_header`

### PR DESCRIPTION
**Pull request by YassinNouh21**
📝 **Summary**
---
**This PR for issue #915**

**Description**
---
This pull request addresses issue #915, which involves centering the header that displays the name of the mosque on the home screen of the mosque. The modification ensures that the header is properly aligned in both LTR and RTL languages.

**Tests**
---
🧪 **Use case 1: English Language Header**
---
💬 **Description:**
Tested the header alignment on the homepage in English. The header is now centered correctly and maintains its position across different screen sizes and devices.

📷 **Screenshots or GIFs (if applicable):**

image

🧪 **Use case 2: Arabic Language Header**
---
💬 **Description:**
Evaluated the header alignment in the Arabic version of the homepage. The RTL (Right-to-Left) layout is correctly handled, and the header remains centered and consistent.

📷 **Screenshots or GIFs (if applicable):**

image

**Checklist:**
---
- [x] **Coding Standards:** I have reviewed my code to ensure it follows the project's coding standards.
- [x] **Testing:** I have tested the changes in both English and Arabic languages, and they work as expected.
- [x] **Merge Conflicts:** I have resolved any merge conflicts with the latest main/development branch.
- [x] **Branch Status:** The branch is up-to-date with the target branch (main/development).

### CODE REVIEW

**Review by ghassenbenzahra123 — COMMENTED** [review]
Please add the changes to landscape_turkish_home also

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Sorry @ghassenbenzahra123 I requested your review again but you have already a non processed comment

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ghassenbenzahra123 Need approve

**Review by ghassenbenzahra123 — APPROVED** [review]
LGTM! good work Yassin

**Review by ibrahim-zehhaf-mawaqit — APPROVED** [review]

**Pull request merged**
