### PR TITLE
766 show video message if announcements mode selected

### PR DESCRIPTION
**Pull request by ismaelAbogabal**
Show video announcements if the user enabled the announcement mode 

Until now the primary/secondary screen has had no effect on the video announcement 
If we should show videos on the secondary screen please let me know so I do it with this pull request

### CODE REVIEW

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> Show video announcements if the user enabled the announcement mode
> 
> Until now the primary/secondary screen has had no effect on the video announcement If we should show videos on the secondary screen please let me know so I do it with this pull request

Thanks @ismaelAbogabal Yes please, show video in secondary mode, but without sound (mute) 
Here is a summary of the video logic

For Mosques 
* Primary screen: Skip video Annoucement 
* Secondary screen : Show and mute video Annoucement 
* Annoucement Mode : Show and mute video Annoucement 

For Homes and others
There is no option for secondary/primary and announcement mode
Show video announcements with sound

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
I did the logic above 

> For Mosques
> 
> Primary screen: Skip video Annoucement
> Secondary screen : Show and mute video Annoucement
> Annoucement Mode : Show and mute video Annoucement

The only issue remaining on this topic is #694
My test video is working just fine so could you give me your mosque id so I can test it from your perspective 

Possible fixes for this would be 
- caching the videos if youtube allows that

**Comment by ibrahim-zehhaf-mawaqit** [comment]
ID 116 it's my home

Tested on 2 boxes Mi 4 and Mi 3, same behaviour

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 

In my last commit 31e2c049b186ed51afebb18a2b7d78650ff312cd. I did enhance the performance of the video announcement by applying repaint boundaries and separating it into its own stateful widget 

This improved the performance of this screen
But I need to work more on the app performance  I will create an issue for that.

**Review by ibrahim-zehhaf-mawaqit — APPROVED** [review]

**Pull request merged**
